// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6o3V6msfYiyuzcpgsiZCm7tnBng_e7k',
    appId: '1:1093367672917:web:c772d4d9d4b2339e1764dc',
    messagingSenderId: '1093367672917',
    projectId: 'amadia-auction',
    authDomain: 'amadia-auction.firebaseapp.com',
    storageBucket: 'amadia-auction.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkn8LN-P0XXTIbG7ZRiP5l7l9rqqZxtzg',
    appId: '1:1093367672917:android:f43f40299f845ca81764dc',
    messagingSenderId: '1093367672917',
    projectId: 'amadia-auction',
    storageBucket: 'amadia-auction.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc7owdJIJZxTSXBhvkwr3lynH3cPbHCdA',
    appId: '1:1093367672917:ios:0eca9fb091b10ed61764dc',
    messagingSenderId: '1093367672917',
    projectId: 'amadia-auction',
    storageBucket: 'amadia-auction.appspot.com',
    androidClientId: '1093367672917-hfdmqibs7vonlfgimccrf0ehthuejgqh.apps.googleusercontent.com',
    iosClientId: '1093367672917-56uehto6uo5jgnft0o5ojr0sl3spflj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuctionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc7owdJIJZxTSXBhvkwr3lynH3cPbHCdA',
    appId: '1:1093367672917:ios:0eca9fb091b10ed61764dc',
    messagingSenderId: '1093367672917',
    projectId: 'amadia-auction',
    storageBucket: 'amadia-auction.appspot.com',
    androidClientId: '1093367672917-hfdmqibs7vonlfgimccrf0ehthuejgqh.apps.googleusercontent.com',
    iosClientId: '1093367672917-56uehto6uo5jgnft0o5ojr0sl3spflj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuctionApp',
  );
}
